# Cpp language
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# Enable caching
cache:
  apt: true
# Build matrix
addons:
  apt:
    sources: 
        - george-edison55-precise-backports
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
    packages:
        - clang-3.7
        - g++-5
        - gcc-5
        - cmake
        - cmake-data
# Install
install:
    - if ["$CXX" = "g++"]; then export CXX="g++-5" CC="gcc-5"; fi
    - if ["$CXX" = "clang++"]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make